### ISSUE TITLE
Exclude hands in Monto-Carlo simulation

### ISSUE THREAD

**Issue by Vingtoft** [fblaha/pokershell#1]
Thank you so much for creating and open sourcing this awesome project! I can't believe it only has 2 stars :-) 

**I have a question/request:** Is it possible to exclude hand combinations in the monte-carlo simulation? 

_Consider the following use case:_ 
On a 6 player table I have AdAs preflop, and raise 5 x BB and an opponent call my raise. 
The flop is: 3h6s5c.
According to the monte-carlo simulation, I have ~38% chance of winning and ~61% chance of losing. 
Of all beating hands, a straight accounts for ~52% and two pairs accounts for ~12%.

The problem is: In order for this flop to be of value to you, your hand must have been really bad preflop. After I raised 5 x BB preflop, its unlikely that opponents with bad hands called, and therefore the chance of my opponents hitting 2 pairs or a straight should be greatly reduced. 

A solution to obtaining this functionality is to add the ability to exclude hands in the monte-carlo simulation. Is this possible?

**Comment by fblaha** [comment]
Thanks for nice words about the project! Sorry for delayed answer.

Unfortunately this project is no longer active. I have no plans to implement new features. Feel free to fork it and do any changes.
